"""Pydantic models for agent roles, decisions, intents, and handoffs."""

from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class AgentRole(str, Enum):
    """Conceptual AI roles in the architecture."""
    MANAGER = "manager"
    CUSTOMER_SERVICE = "customer_service"
    SUPPORT = "customer_service"  # Alias for Customer Service
    SALES = "sales"
    ROUTER = "router"


class UserIntent(str, Enum):
    """Classified customer conversational intents."""
    # Lifecycle & Conversational
    GREETING = "GREETING"
    CLOSING = "CLOSING"
    CONFIRMATION = "CONFIRMATION"

    # Sales domain
    PRODUCT_ENQUIRY = "PRODUCT_ENQUIRY"
    PRICING = "PRICING"
    OFFER = "OFFER"
    AVAILABILITY = "AVAILABILITY"
    
    # Support domain
    PRODUCT_USAGE = "PRODUCT_USAGE"
    TROUBLESHOOTING = "TROUBLESHOOTING"
    WARRANTY = "WARRANTY"
    INSTALLATION = "INSTALLATION"
    MAINTENANCE = "MAINTENANCE"
    ORDER_SUPPORT = "ORDER_SUPPORT"
    REFUND_REPLACEMENT = "REFUND_REPLACEMENT"
    COMPLAINT = "COMPLAINT"
    
    # Ambiguous / General
    UNKNOWN = "UNKNOWN"


class Department(str, Enum):
    """Business departments selectable at IVR entry."""
    SALES = "SALES"
    CUSTOMER_SERVICE = "CUSTOMER_SERVICE"


class CallLifecycleStage(str, Enum):
    """Conversational lifecycle stage of a phone call."""
    IVR_LANGUAGE_SELECTION = "IVR_LANGUAGE_SELECTION"
    IVR_DEPARTMENT_SELECTION = "IVR_DEPARTMENT_SELECTION"
    CONVERSATION_ACTIVE = "CONVERSATION_ACTIVE"
    CALL_START = "CALL_START"
    GREETING = "GREETING"
    INTENT_DISCOVERY = "INTENT_DISCOVERY"
    ACTIVE_RESOLUTION = "ACTIVE_RESOLUTION"
    FOLLOW_UP = "FOLLOW_UP"
    HANDOFF = "HANDOFF"
    CLOSING = "CLOSING"
    CALL_END = "CALL_END"


class EscalationReason(str, Enum):
    """Triggers prompting the Manager agent to intervene."""
    UNKNOWN_ANSWER = "unknown_answer"
    RETRIEVAL_FAILED = "retrieval_failed"
    INSUFFICIENT_KNOWLEDGE = "insufficient_knowledge"
    LOW_CONFIDENCE = "low_confidence"
    UNGROUNDED_FACT = "ungrounded_fact"
    CUSTOMER_FRUSTRATION = "customer_frustration"
    WRONG_SPECIALIST = "wrong_specialist"
    REPEATED_FAILURES = "repeated_failures"
    HUMAN_REQUESTED = "human_requested"


class ManagerAction(str, Enum):
    """Decisive supervisory actions taken by the Manager agent."""
    CONTINUE = "continue"
    GUIDE = "guide"
    ATTACH_AGENT = "attach_agent"
    ESCALATE_HUMAN = "escalate_human"


class ManagerDecision(BaseModel):
    """Action determined by the Manager supervisory agent."""
    action: ManagerAction = Field(description="Action to take: continue, guide, attach_agent, escalate_human")
    guidance: Optional[str] = Field(default=None, description="Coaching, safety boundaries, or context for the agent")
    target_agent: Optional[AgentRole] = Field(default=None, description="Specialist agent to attach/transfer to")
    escalation_reason: Optional[EscalationReason] = None
    reasoning: str = Field(description="Supervisory reasoning explaining this decision")


class KnowledgeGroundingStatus(BaseModel):
    """Model tracking verification of retrieved evidence."""
    is_grounded: bool = True
    knowledge_available: bool = True
    confidence: float = 1.0
    citations: List[str] = Field(default_factory=list)
    missing_facts: List[str] = Field(default_factory=list)


class AgentResponse(BaseModel):
    """Direct turn response generated by an AI agent."""
    agent_role: AgentRole
    text: str
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    requires_manager_review: bool = False
    manager_trigger: Optional[EscalationReason] = None
    suggested_specialist: Optional[AgentRole] = None
    citations: List[str] = Field(default_factory=list)
    is_grounded: bool = True
    metadata: Dict[str, Any] = Field(default_factory=dict)
